config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users
  resources :assignments, except: [:destroy]
  delete 'assignments/:id' => 'assignments#destroy'
  resources :sessions, except: [:destroy]
  delete '/logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  validates :title, :body, :category, :link, :assignment_number, presence:true
  validates :link, uniqueness:true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :assignments
    validates :email, :name, :surname, :password, presence:true, on: :create
    validates :email, uniqueness:true
    validates :email, format: /\w+@\w+\.{1}[a-zA-Z]{2,}/, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :authorize, :student?, :access, :assignment_access, :report_links

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
  
    def logged_in?
      !!current_user
    end
  
    def authorize
      unless logged_in?
        flash[:danger] = "You must be logged in to do that."
        redirect_to new_session_path unless logged_in?
      end
    end

    def student?
      current_user.user_type == "Student"
    end

    def access
      @user = User.find_by_id params[:id]
      unless current_user == @user
        redirect_to user_path(current_user)
      end
    end
    
    def assignment_access
      if !Assignment.exists?(params[:id])
        redirect_to user_path(current_user)
      else
        @assignment = Assignment.find(params[:id])
      
        if student? && current_user.id != @assignment.user_id
            redirect_to user_path(current_user)
        elsif !student? && @assignment.submit == "No"
          redirect_to user_path(current_user)
        end
      end
    end

    def report_links
      @reports = Assignment.where(submit:"Yes").order('updated_at DESC')
    end 
    
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :authorize
  before_action :assignment_access, except: [:index, :new, :create]  
  before_action :report_links
  

  def index
    @user = User.find_by_id current_user.id
    @submitted = @user.assignments.where(submit:"Yes").reverse
    @in_prog = @user.assignments.where(submit:"No").reverse.each
    @assignments = Assignment.where(submit:"Yes")
    @students = User.where(user_type:"Student")
  end

  def show
    @assignment = Assignment.find(params[:id])
  end

  def new
    @assignment = Assignment.new
  end

  def create
    @user = User.find_by_id current_user.id
    @assignment = Assignment.new(assignment_params)
    @assignment.user_id = current_user.id
    if @assignment.save
      flash[:success] = "Your report has been saved."
      redirect_to user_path(@user)
    else
      flash[:warning] = "Your report did not submit. Please try again."
      redirect_to new_assignment_path
    end
  end

  def edit
    @assignment = Assignment.find(params[:id])
    if @assignment.submit == "Yes"
      redirect_to assignment_path(@assignment)
    end
  end

  def update
    @assignment = Assignment.find(params[:id])
    if @assignment.update(assignment_params)
      flash[:success] = "Your changes have been saved."
      redirect_to assignment_path(@assignment)
    else 
      flash[:warning] = "Your changes were not saved. Please check all of your fields."
      redirect_to edit_assignment_path
    end
  end

  def destroy
    @assignment = Assignment.find(params[:id])
    if @assignment.destroy
      flash[:danger] = "Your report has been deleted."
      redirect_to user_path(current_user)
    end
  end


  private
  def assignment_params
    params.require(:assignment).permit(:title, :body, :category, :link, :submit, :assignment_number)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :report_links
  
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      if @user.user_type == "Teacher"
          redirect_to user_path(@user)
      else
          redirect_to user_path(@user)
      end
    else 
      flash[:alert] = "Incorrect email or password."
      redirect_to new_session_path
    end
  end

  def destroy
    redirect_to new_session_path
    session[:user_id] = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
  before_action :authorize, only: [:show, :edit, :update, :destroy]  
  before_action :report_links
  before_action :access, except: [:index]
  
  def index
  end

  def show
    @user = User.find(params[:id])
    if student?
      @assignment = Assignment.new
    else
      @students = User.where(user_type:"Student")
      @assignments = Assignment.where(submit:"Yes")
    end
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.code == "1234"
      @user.user_type = "Teacher"
      if @user.save
        session[:user_id] = @user.id
        flash[:success] = "Your account was created!"
        redirect_to user_path(@user)
      else
        if !!@user.email
          flash[:warnning] = "This email address may be formatted incorrectly or may already be in use."
          redirect_to new_user_path
        elsif
          @user.password == '' || @user.password_confirmation == ''
          flash[:warning] = "Plesae enter and confirm password."
          redirect_to new_user_path
        else
          flash[:warning] = "Your account was not created. Please complete all fields." 
          redirect_to new_user_path
        end
      end
    elsif @user.code == ''
      @user.user_type = "Student"
      if @user.save
        session[:user_id] = @user.id
        flash[:success] = "Your account was created!"
        redirect_to user_path(@user)
      else
        if !!@user.email
          flash[:warning] = "This email address may be formatted incorrectly or may already be in use."
          redirect_to new_user_path
        elsif
          @user.password == '' || @user.password_confirmation == ''
          flash[:warning] = "Plesae enter and confirm password."
          redirect_to new_user_path
        else
          flash[:warning] = "Your account was not created. Please complete all fields." 
          redirect_to new_user_path
        end
      end
    else
      flash[:warning] = "Your account was not created. Please check all fields."
      redirect_to new_user_path
    end 
  end

  def edit
    @user = User.find_by_id current_user.id
  end

  def update
    @user = User.find_by_id current_user.id
    if @user.update(user_params)
      flash[:success] = "Your changes have been saved."
      redirect_to user_path(@user)
    else 
      flash[:warning] = "Your changes were not saved. Please check all of your fields."
      redirect_to edit_user_path
    end
  end

  def destroy
    @user = User.find_by_id current_user.id
    if @user.user_type == "Teacher"
      session[:user_id] = nil
      if @user.destroy
        flash[:danger] = "Your account has been permanently deleted."
        redirect_to new_session_path
      end
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :surname, :email, :current_password, :password, :password_confirmation, :code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/assignments/edit.html.erb
<div class="jumbotron">
    <div class="jumbotron-overlay">
        <small><%= student? ? "Student Account" : "Teacher Account" %> - Edit Profile</small>
        <h1 class="display-3"><%= "#{current_user.name} #{current_user.surname}" %></h1>
    </div>
</div>

<div class="formish">
    <h1 class="form_head">Edit Assignment</h1>
    <%= form_for @assignment do |f| %>
        <div class="form-group">
            <%= f.label :assignment_number, "Assignment number" %>
            <%= f.number_field :assignment_number, class:"form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :title, "Title of Article" %>
            <%= f.text_field :title, class:"form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :body, "Science Reporter" %>
            <%= f.text_area :body, class:"form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :category, "Category of Article" %>
            <%= f.text_field :category, class:"form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :link, "Link to Article" %>
            <%= f.text_field :link, class:"form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :submit, "Are you ready to submit?" %>
            <%= f.select :submit, ["No", "Yes"], class:"form-control" %>
        </div>
        <%= f.submit "Update", class:"btn btn-primary" %>
        <%= link_to "Cancel", assignment_path, class:"btn btn-secondary" %>
        <%= link_to "Delete", assignment_path, data: {confirm: "Are you sure you want to delete this report? This cannot be undone."}, method: 'delete', class:"btn btn-danger" %>
    <% end %>
</div>

app/views/assignments/index.html.erb
<div class="jumbotron">
    <div class="jumbotron-overlay">
        <small><%= student? ? "Student Account - Assignments" : "Teacher Account - Assignments" %></small>
        <h1 class="display-3"><%= "#{@user.name} #{@user.surname}" %></h1>
    </div>
</div>

<% if student? %>
    <%= render 'assignments/partials/student_assignment_index' %>
<% else %>
    <%= render 'assignments/partials/teacher_assignment_index' %> 
<% end %>

app/views/assignments/new.html.erb
<div class="jumbotron">
    <div class="jumbotron-overlay">
        <small><%= student? ? "Student Account" : "Teacher Account" %> - New Assignment</small>
        <h1 class="display-3"><%= "#{current_user.name} #{current_user.surname}" %></h1>
    </div>
</div>

<div class="formish">
    <h1 class="form_head">New Assignment</h1>
    <%= form_for @assignment do |f| %>
        <div class="form-group">
            <%= f.label :title, "Title of Article" %>
            <%= f.text_field :title, class:"form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :link, "Link to Article" %>
            <%= f.text_field :link, class:"form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :body, "Science Reporter" %>
            <%= f.text_area :body, class:"form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :category, "Category of Article" %>
            <%= f.text_field :category, class:"form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :assignment_number, "Assignment number" %>
            <%= f.number_field :assignment_number, class:"form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :submit, "Are you ready to submit?" %>
            <%= f.select :submit, ["No", "Yes"], class:"form-control" %>
        </div>
        <%= f.submit "Save", class:"btn btn-primary" %>
        <%= link_to "Cancel", url_for(:back), class:"btn btn-secondary" %>
    <% end %>
</div>

app/views/assignments/partials/_by_assgn.html.erb
<% @assignments.order("assignment_number DESC").each do |s| %>
    <%= "Assignment Number #{s.assignment_number}" %>
    <div class="clear"></div>
    <% @assignments.where(assignment_number:"#{s.assignment_number}").each do |a| %>
        <%= render 'layouts/partials/card', :a => a %>
    <% end %>
    <div class="clear"></div>
<% end %>

app/views/assignments/partials/_by_student.html.erb
<% @students.each do |s| %>
    <%= "#{s.name} #{s.surname}" %><br />
    <% @assignments.where(user_id:"#{s.id}").reverse.each do |a| %>
        <%= render 'layouts/partials/card', :a => a %>
      <% end %>
      <div class="clear"></div>
<% end %>

app/views/assignments/partials/_student_assignment_index.html.erb
    <div class="btn btn-outline-primary" data-toggle="collapse" data-target="#submitted">See Submitted</div>
    <div class="btn btn-outline-primary" data-toggle="collapse" data-target="#in_prog">See In Progress</div>
    <%= link_to "Post a new assignment", new_assignment_path, class:'btn btn-outline-primary' %>
    <%= link_to "Back to Profile", user_path(current_user), class:"btn btn-outline-primary" %>

    <div class="panel-collapse collapse" id="submitted"> 
        <hr />
        <h3>Submitted</h3>        
        <% @submitted.each do |a| %>
            <%= render 'layouts/partials/card', :a => a %>
        <% end %>
    </div>

    <div class="clear"></div>

    <div class="panel-collapse collapse in" id="in_prog"> 
        <hr />        
        <h3>In Progress</h3>
        <% @user.assignments.where(submit:"No").reverse.each do |a| %>
            <%= render 'layouts/partials/card', :a => a %>
        <% end %>
    </div>

    <div class="clear"></div>

app/views/assignments/partials/_teacher_assignment_index.html.erb
    <!-- <div class="btn btn-outline-primary" data-toggle="collapse" data-target="#by_assignment">By Assignment</div> -->
    <div class="btn btn-outline-primary" data-toggle="collapse" data-target="#by_student">By Student</div>
    <%= link_to "Back to Profile", user_path(current_user), class:"btn btn-outline-primary" %>


    <!-- <div class="panel-collapse collapse" id="by_assignment"> 
        <hr />
        <h3>By Assignment</h3>        
        <%= render 'assignments/partials/by_assgn' %>
    </div> -->

    <div class="clear"></div>

    <div class="panel-collapse collapse in" id="by_student"> 
        <hr />
        <h3>By Student</h3>
        <%= render 'assignments/partials/by_student' %>
    </div>

    <div class="clear"></div>

app/views/assignments/show.html.erb
<div class="jumbotron">
    <div class="jumbotron-overlay">
        <small>Science Reporter by</small>
        <h1 class="display-3"><%= "#{@assignment.user.name} #{@assignment.user.surname}" %></h1>
    </div>
</div>

<div class="show-assignment">
    <h1><%= @assignment.title %></h1>
    <p><%= @assignment.body %></p>
    <p>Article Category: <%= @assignment.category %></p>
    <p>Link to Article: <%= link_to @assignment.link, @assignment.link, target:"_blank" %></p>
    <% if @assignment.submit == "No" %>
        <%= link_to "Edit", "/assignments/#{@assignment.id}/edit", class:'btn btn-primary' %>       
    <% end %>
    <%= link_to "All Assignments", assignments_path, class:"btn btn-secondary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Science Reporter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Pangolin" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="root/favicon.ico" type="image/x-icon">
    <link rel="icon" href="../../../favicon.ico" type="image/x-icon">
  </head>

  <body>
      <%= render 'layouts/partials/navbar' %>
      <%= render 'layouts/partials/flash' %> 
      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-9"> <%= yield %></div>
          <div class="col-sm-3">
            <div class="sidebar">
              <h4>Latest Articles</h4>
              <div class="list">
                <% @reports.take(10).each do |a| %>
                  <%= link_to a.title, "#{a.link}", target:"_blank" %><br />
                <% end %>
              </div>
            </div>
          </div>
        </div>
    </div>
  </body>
</html>

app/views/layouts/partials/_card.html.erb
<div class="card" style="width: 20rem;">
    <div class="card-body">
        <h4 class="card-title"><%= link_to a.title.truncate(40), "/assignments/#{a.id}" %></h4>
        <h6 class="card-subtitle mb-2 text-muted"><%= "by #{a.user.name} #{a.user.surname}" %></h6>                        
        <p class="card-text"><%= a.body.truncate(80) %></p>
        <%= link_to "Read More", "/assignments/#{a.id}", class:'card-link' %>
    </div>
    <div class="card-footer text-muted">
        <%= a.submit == "Yes" ? "Submitted:" : "Last Update:" %>
        <%= "#{a.updated_at.in_time_zone('EST').strftime("%a, %b %e, %Y at  %l:%M%P")} -- Report ##{a.assignment_number}" %>
    </div>
</div>

app/views/layouts/partials/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/layouts/partials/_navbar.html.erb
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="navbar-brand" href="#">Science Reporter</div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto p-2">
            <li class="nav-item">
                <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <% if logged_in? %>  
                <li class="nav-item">
                    <%= link_to "Logged in as #{current_user.name} #{current_user.surname}", user_path(current_user), class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Log Out", logout_path, method: 'delete', class: "nav-link" %>
                </li>
            <% else %>
                <li class="nav-item"> 
                    <%= link_to "Log In", new_session_path, class: "nav-link" %>
                </li>
                <li class="nav-item"> 
                    <%= link_to "Sign Up", new_user_path, class: "nav-link" %>
                </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/students/show.html.erb
<div class="jumbotron">
    <small>Student Account</small>
    <h1 class="display-3"><%= "#{@user.name} #{@user.surname}" %></h1>
    <hr class="my-4">
    <!-- <p>It uses utility classes for typography and spacing to space content out within the larger container.</p> -->
    
    <h3>Recently Submitted</h3>
    <% @user.assignments.where(submit:"Yes").order('updated_at DESC').take(2).each do |a| %>
    <div class="card" style="width: 20rem;">
        <div class="card-body">
            <h4 class="card-title"><%= link_to a.title.truncate(40), "/assignments/#{a.id}" %></h4>
            <p class="card-text"><%= a.body.truncate(80) %></p>
            <%= link_to "Read More", "/assignments/#{a.id}", class:'card-link' %>
            <!-- <%= link_to "Article Link", "#{a.link}", class:'card-link' %> -->
        </div>
        <div class="card-footer text-muted">
            <%= "Last updated: #{a.updated_at.in_time_zone('EST').strftime("%a, %b %e, %Y at  %l:%M%P")}" %>
        </div>
    </div>
    <% end %>
    <div class="clear"></div>
    <p class="lead">
        <%= link_to "See all assignments", assignments_path, class:'btn' %>
        <%= link_to "Post a new assignment", new_assignment_path, class:'btn' %>
        <%= link_to "Change Password", edit_student_path, class:'btn' %>
        
    </p>

</div>
    
      
      
    

app/views/teachers/show.html.erb
<h1><%= "#{@teacher.name} #{@teacher.surname}" %></h1>

<h2>List of All Students</h2>

<% @students.each do |s| %>
    <%= "#{s.name} #{s.surname}" %><br />
    <% @assignments.where(user_id:"#{s.id}").reverse.each do |a| %>
    <div class="card" style="width: 20rem;">
          <div class="card-body">
              <h4 class="card-title"><%= link_to a.title.truncate(40), "/assignments/#{a.id}" %></h4>
              <!-- <h6 class="card-subtitle mb-2 text-muted"><%= "#{s.name} #{s.surname}" %></h6> -->
              <p class="card-text"><%= a.body.truncate(80) %></p>
              <%= link_to "Read More", "/assignments/#{a.id}", class:'card-link' %>
              <!-- <%= link_to "Article Link", "#{a.link}", class:'card-link' %> -->
          </div>
          <div class="card-footer text-muted">
                <%= "Last updated: #{a.updated_at.in_time_zone('EST').strftime("%a, %b %e, %Y at %l:%M%P")}" %>
            </div>
      </div>
      <% end %>
      <div class="clear"></div>
<% end %>

<!-- <% @assignments.reverse.each do |a| %>
<div class="card" style="width: 20rem;">
      <div class="card-body">
          <h4 class="card-title"><%= link_to a.title.truncate(40), "/assignments/#{a.id}" %></h4>
          <p class="card-text"><%= a.body.truncate(80) %></p>
          <%= link_to "Read More", "/assignments/#{a.id}", class:'card-link' %>
          <%= link_to "Article Link", "#{a.link}", class:'card-link' %>
      </div>
  </div>
  <% end %> -->






  <div class="clear"></div>
  
<br />
<br />
<%= link_to "Edit Profile", edit_teacher_path %>

app/views/users/edit.html.erb
<div class="jumbotron">
    <div class="jumbotron-overlay">
        <small><%= student? ? "Student Account" : "Teacher Account" %> - Edit Profile</small>
        <h1 class="display-3"><%= "#{@user.name} #{@user.surname}" %></h1>
    </div>
</div>

<div class="formish">
    <%= form_for @user do |f| %>
        <% unless @user.user_type == "Student" %>
            <h1 class="form_head">Edit Profile</h1>
            <h3>Change Profile Info</h3>
            <div class="form-group">
                <%= f.label :name, "First Name" %>
                <%= f.text_field :name, class:"form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :surname, "Last Name" %>
                <%= f.text_field :surname, class:"form-control"  %>
            </div>
            <div class="form-group">
                <%= f.label :email, "Email Address" %>
                <%= f.text_field :email, class:"form-control"  %>
            </div>
        <% end %>
            
            <h3>Change Password</h3>
            <div class="form-group">
                <%= f.label :password, "New Password" %>
                <%= f.password_field :password, class:"form-control"  %>
            </div>
            <div class="form-group">
                <%= f.label :password_confirmation, "Confirm New Password" %>
                <%= f.password_field :password_confirmation, class:"form-control"  %>
            </div>
            <%= f.submit "Update", class:"btn btn-primary" %>
            <%= link_to "Cancel", user_path(current_user), class:"btn btn-secondary" %>
            <% unless @user.user_type == "Student" %>
                <%= link_to "Delete Account", user_path(current_user), data: {confirm: "Are you sure you want to delete your account? This cannot be undone."}, method: 'delete', class:"btn btn-danger" %>
            <% end %>
    <% end %>
</div>

app/views/users/index.html.erb
<div class="jumbotron">
    <div class="jumbotron-overlay">
        <h1 class="display-3">Yay Science!</h1>
        <p class="lead"> And yay learning. In seventh grade, we focus on Life Science - hence the cells - but we don't want to limit ourselves to learning about only human biology. Each week, students will find a science-related article that piques their interest and submit an abstract. </p>
        <hr class="my-4">
        <p>In this app, students are able to work on and submit their "Science Reporter" assignments. It's also a place to check out the articles that students have reported on thus far - see the latest listed on the right!</p>
        <p class="lead">
            <% if logged_in? %>
                <%= link_to "Go To Your Profile", user_path(current_user), class:"btn btn-primary btn-lg" %>
            <% else %>
                <%= link_to "Log In", new_session_path, class:"btn btn-primary btn-lg" %>
                <%= link_to "Sign Up", new_user_path, class:"btn btn-primary btn-lg" %> 
            <% end %>
        </p>
    </div>  
</div>

<p><strong>How to use this portal:</strong> <%= link_to"Log in", new_session_path %> or <%= link_to "create an account", new_user_path %>, then post your Science Reporter assignments. Feel free to keep coming back to work on your assignment until you're ready to submit it. </p>

app/views/users/new.html.erb
<div class="jumbotron">
    </div>
<div class="formish">
    <h1 class="form_head">Sign Up</h1>
    <%= form_for @user do |f| %>
        <div class="form-group">
            <%= f.label :name, "First Name" %>
            <%= f.text_field :name, class:'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :surname, "Last Name" %>
            <%= f.text_field :surname, class:'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :email, "Email Address" %>
            <%= f.text_field :email, class:'form-control' %>
        </div>
            <div class="form-group">
            <%= f.label :password, "Password" %>
            <%= f.password_field :password, class:'form-control' %>
        </div>
            <div class="form-group">
            <%= f.label :password_confirmation, "Confirm Password" %>
            <%= f.password_field :password_confirmation, class:'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :code, "Teacher Code" %>
            <%= f.text_field :code, class:'form-control' %>
        </div>
        <%= f.submit "Sign Up", class:'btn btn-primary' %>
    <% end %>
</div>

app/views/users/partials/_show_student.html.erb
    <h3>Recently Submitted</h3>
    <% @user.assignments.where(submit:"Yes").order('updated_at DESC').take(2).each do |a| %>
        <%= render 'layouts/partials/card', :a => a %>
    <% end %>
    <div class="clear"></div>
    <p class="lead">
        <%= link_to "See all assignments", assignments_path, class:'btn' %>
        <%= link_to "Post a new assignment", new_assignment_path, class:"btn" %>
        <%= link_to "Change Password", edit_user_path, class:'btn' %>
    </p>

app/views/users/partials/_show_teacher.html.erb
    <h3>Recently Submitted</h3>
    <% @assignments.where(submit:"Yes").order('updated_at DESC').take(2).each do |a| %>
        <%= render 'layouts/partials/card', :a => a %>
    <% end %>
    <div class="clear"></div>
    <p class="lead">
        <%= link_to "See all submitted reports", assignments_path, class:'btn' %>
        <%= link_to "Edit Profile", edit_user_path, class:'btn' %>
    </p>

app/views/users/show.html.erb
<div class="jumbotron">
    <div class="jumbotron-overlay">
        <small><%= student? ? "Student Account" : "Teacher Account" %></small>
        <h1 class="display-3"><%= "#{@user.name} #{@user.surname}" %></h1>
    </div>
</div>

<% if @user.user_type == "Teacher" %>
    <%= render 'users/partials/show_teacher' %> 
<% elsif @user.user_type == "Student" %>
    <%= render 'users/partials/show_student' %>
<% end %>